version: '3.8'

services:
  frontend:
    image: faqihnafiddin/frontend:latest
    ports:
      - "5173:5173"

  backend:
    image: faqihnafiddin/backend:latest
    ports:
      - "5000:5000"

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    # Tambahkan ini agar Prometheus bisa memanggil 'localhost:9100' atau service lain dengan lancar
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    network_mode: "host"
    pid: "host"
    volumes:
      - '/:/host:ro,rslave'